sudo: false
language: elixir
otp_release:
  - 20.1
elixir:
  - 1.6.0
cache:
  directories:
    - /home/travis/.mix/
before_install:
  - mkdir -p priv/test/ssh_keys
  - ssh-keygen -N '' -b 256 -t ecdsa -f priv/test/ssh_keys/ssh_host_ecdsa_key
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - mix test
  - MIX_ENV=test mix dialyzer
